### ISSUE TITLE
友達を作る機能の実装

### ISSUE THREAD

**Issue by riku6460** [knh8205/Tomato#5]

**Comment by knh8205** [comment]
ユーザー検索を実装予定です。ご期待下さい。

**Comment by riku6460** [comment]
友達が勝手に作られることはありますか？

**Comment by knh8205** [comment]
チュートリアルアカウントが最初にフォローする仕様も策定中ですが、他のアカウントを無断にフォローする仕様はありません。

**Comment by riku6460** [comment]
チュートリアルさんと友達になれるのですか？？？？？

**Comment by knh8205** [comment]
そう考えたほうが幸せだと思います。
